EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'SOE_DATABASE'
GO
use [SOE_DATABASE];
GO
use [master];
GO
USE [master]
GO
ALTER DATABASE [SOE_DATABASE] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
USE [master]
GO
/****** Object:  Database [SOE_DATABASE]    Script Date: 11/08/2020 11:01:05 p. m. ******/
DROP DATABASE [SOE_DATABASE]
GO
CREATE DATABASE SOE_DATABASE
GO
USE SOE_DATABASE
GO
CREATE TABLE USER_TYPES
(
 ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 DESCRIPTION VARCHAR(100) NOT NULL
)
GO
INSERT INTO USER_TYPES VALUES('Regular user');
INSERT INTO USER_TYPES VALUES('Tester');
INSERT INTO USER_TYPES VALUES('Admin');
GO
CREATE TABLE SCHOOLS
( 
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NAME VARCHAR(100) NOT NULL,
HOME_PAGE VARCHAR(100) NOT NULL,
IMG_PATH VARCHAR(100) NOT NULL
)
GO
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 1','https://www.saes.cecyt1.ipn.mx/','https://www.saes.cecyt1.ipn.mx/Images/logos/01.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 2','https://www.saes.cecyt2.ipn.mx/','https://www.saes.cecyt2.ipn.mx/Images/logos/02.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 3','https://www.saes.cecyt3.ipn.mx/','https://www.saes.cecyt3.ipn.mx/Images/logos/03.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 4','https://www.saes.cecyt4.ipn.mx/','https://www.saes.cecyt4.ipn.mx/Images/logos/04.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 5','https://www.saes.cecyt5.ipn.mx/','https://www.saes.cecyt5.ipn.mx/Images/logos/05.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 6','https://www.saes.cecyt6.ipn.mx/','https://www.saes.cecyt6.ipn.mx/Images/logos/06.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 7','https://www.saes.cecyt7.ipn.mx/','https://www.saes.cecyt7.ipn.mx/Images/logos/07.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 8','https://www.saes.cecyt8.ipn.mx/','https://www.saes.cecyt8.ipn.mx/Images/logos/08.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 9','https://www.saes.cecyt9.ipn.mx/','https://www.saes.cecyt9.ipn.mx/Images/logos/09.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 10','https://www.saes.cecyt10.ipn.mx/','https://www.saes.cecyt10.ipn.mx/Images/logos/10.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 11','https://www.saes.cecyt11.ipn.mx/','https://www.saes.cecyt11.ipn.mx/Images/logos/11.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 12','https://www.saes.cecyt12.ipn.mx/','https://www.saes.cecyt12.ipn.mx/Images/logos/12.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 13','https://www.saes.cecyt13.ipn.mx/','https://www.saes.cecyt13.ipn.mx/Images/logos/13.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 14','https://www.saes.cecyt14.ipn.mx/','https://www.saes.cecyt14.ipn.mx/Images/logos/14.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CECyT 15','https://www.saes.cecyt15.ipn.mx/','https://www.saes.cecyt15.ipn.mx/Images/logos/15.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CET 1','https://www.saes.cet1.ipn.mx/','https://www.saes.cet1.ipn.mx/Images/logos/17.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESIME CULHUACÁN','https://www.saes.esimecu.ipn.mx/','https://www.saes.esimecu.ipn.mx/Images/logos/35.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESIME AZCAPOTZALCO','https://www.saes.esimeazc.ipn.mx/','https://www.saes.esimeazc.ipn.mx/Images/logos/36.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESIME TICOMÁN','https://www.saes.esimetic.ipn.mx/','https://www.saes.esimetic.ipn.mx/Images/logos/37.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESIME ZACATENCO','https://www.saes.esimez.ipn.mx/','https://www.saes.esimez.ipn.mx/Images/logos/30.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESIA TECAMACHALCO','https://www.saes.esiatec.ipn.mx/','https://www.saes.esiatec.ipn.mx/Images/logos/38.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESIA TICOMÁN','https://www.saes.esiatic.ipn.mx/','');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESIA ZACATENCO','https://www.saes.esiaz.ipn.mx/','https://www.saes.esiaz.ipn.mx/Images/logos/31.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CICS MILPA ALTA','https://www.saes.cicsma.ipn.mx/','https://www.saes.cicsma.ipn.mx/Images/logos/61.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('CICS SANTO TOMAS','https://www.saes.cicsst.ipn.mx/','https://www.saes.cicsst.ipn.mx/Images/logos/65.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESCA SANTO TOMAS','https://www.saes.escasto.ipn.mx/','https://www.saes.escasto.ipn.mx/Images/logos/40.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESCA TEPEPAN','https://www.saes.escatep.ipn.mx/','https://www.saes.escatep.ipn.mx/Images/logos/43.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ENCB','https://www.saes.encb.ipn.mx/','');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ENMH','https://www.saes.enmh.ipn.mx/','https://www.saes.enmh.ipn.mx/Images/logos/52.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESEO','https://www.saes.eseo.ipn.mx/','https://www.saes.eseo.ipn.mx/Images/logos/53.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESM','https://www.saes.esm.ipn.mx/','https://www.saes.esm.ipn.mx/Images/logos/51.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESE','https://www.saes.ese.ipn.mx/','https://www.saes.ese.ipn.mx/Images/logos/41.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('EST','https://www.saes.est.ipn.mx/','https://www.saes.est.ipn.mx/Images/logos/42.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('UPIBI','https://www.saes.upibi.ipn.mx/','https://www.saes.upibi.ipn.mx/Images/logos/62.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('UPIICSA','https://www.saes.upiicsa.ipn.mx/','https://www.saes.upiicsa.ipn.mx/Images/logos/60.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('UPIITA','https://www.saes.upiita.ipn.mx/','https://www.saes.upiita.ipn.mx/Images/logos/64.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESCOM','https://www.saes.escom.ipn.mx/','https://www.saes.escom.ipn.mx/Images/logos/63.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESFM','https://www.saes.esfm.ipn.mx/','https://www.saes.esfm.ipn.mx/Images/logos/33.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESIQUE','https://www.saes.esiqie.ipn.mx/','https://www.saes.esiqie.ipn.mx/Images/logos/32.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ESIT','https://www.saes.esit.ipn.mx/','https://www.saes.esit.ipn.mx/Images/logos/34.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('UPIIG','https://www.saes.upiig.ipn.mx/','https://www.saes.upiig.ipn.mx/Images/logos/66.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('UPIIH','https://www.saes.upiih.ipn.mx/','https://www.saes.upiih.ipn.mx/Images/logos/68.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('UPIIZ','https://www.saes.upiiz.ipn.mx/','');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('ENBA','https://www.saes.enba.ipn.mx/','https://www.saes.enba.ipn.mx/Images/logos/44.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('UPIIC','https://www.saes.upiic.ipn.mx/','https://www.saes.upiic.ipn.mx/Images/logos/69.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('UPIIP','https://www.saes.upiip.ipn.mx/','https://www.saes.upiip.ipn.mx/Images/logos/70.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('UPIEM','https://www.saes.upiem.ipn.mx/','https://www.saes.upiem.ipn.mx/Images/logos/45.png');
INSERT INTO SCHOOLS (NAME,HOME_PAGE,IMG_PATH) VALUES ('UPIIT','https://www.saes.upiit.ipn.mx/','https://www.saes.upiit.ipn.mx/Images/logos/71.png');
GO
CREATE TABLE DAYS
(
 ID INT IDENTITY(0,1) PRIMARY KEY NOT NULL,
 NAME VARCHAR(10)
)
GO
INSERT INTO DAYS(NAME) VALUES ('Domingo');
INSERT INTO DAYS(NAME) VALUES ('Lunes');
INSERT INTO DAYS(NAME) VALUES ('Martes');
INSERT INTO DAYS(NAME) VALUES ('Miércoles');
INSERT INTO DAYS(NAME) VALUES ('Jueves');
INSERT INTO DAYS(NAME) VALUES ('Viernes');
INSERT INTO DAYS(NAME) VALUES ('Sabado');
GO
CREATE TABLE CAREERS(
 ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 NAME VARCHAR(100) NOT NULL
)
GO
CREATE TABLE USERS(
 ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 GUID UNIQUEIDENTIFIER DEFAULT newid() UNIQUE NOT NULL,
 TYPE INT FOREIGN KEY REFERENCES USER_TYPES,
 NAME VARCHAR(100) NOT NULL,
 BOLETA VARCHAR(20) UNIQUE NOT NULL,
 MAIL VARCHAR(100)  UNIQUE NOT NULL,
 PASSWORD_PIN VARCHAR(50) NOT NULL, --Contraseña de la aplicación
 STRIKES INT DEFAULT 0,
 BANNED BIT DEFAULT 0,
 DELETED BIT DEFAULT 0,
 VERIFIED_EMAIL BIT DEFAULT 0
)
GO
CREATE TABLE USERS_SCHOOLS
(
 ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 GUID UNIQUEIDENTIFIER DEFAULT newid() UNIQUE NOT NULL,
 CAREER_ID INT FOREIGN KEY REFERENCES CAREERS,
 SCHOOL_ID INT FOREIGN KEY REFERENCES SCHOOLS,
 USER_ID INT FOREIGN KEY REFERENCES USERS NOT NULL,
 ENROLL_DATE DATETIME NOT NULL DEFAULT GETDATE() --fecha en la que comezó a utilizar la app
)
GO
CREATE TABLE DEVICES(
 ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 GUID UNIQUEIDENTIFIER DEFAULT newid() UNIQUE NOT NULL,
 USER_ID INT FOREIGN KEY REFERENCES USERS NOT NULL,
 DEVICE_KEY  VARCHAR(100) UNIQUE NOT NULL,
 BRAND VARCHAR(100) NOT NULL DEFAULT 'GENERIC',
 PLATFORM VARCHAR(100) NOT NULL DEFAULT 'GENERIC',
 MODEL VARCHAR(100) NOT NULL DEFAULT 'GENERIC',
 NAME VARCHAR(100) NOT NULL DEFAULT 'GENERIC',
 LAST_TIME_SEEN DATETIME NOT NULL DEFAULT GETDATE(),
 ENABLED BIT DEFAULT 1
)
GO
CREATE TABLE APP_COLORS
(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
IDENTIFIER VARCHAR(50) UNIQUE,
COLOR VARCHAR(10),
DARK_COLOR VARCHAR(10),
)
GO
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_10','#FCF400','#F0E800')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_11','#fef69e','#E9DA33')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_12','#f2a0a1','#EE6B6D')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_13','#b5ead7','#508676')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_14','#c7ceea','#4c5576')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_15','#d9d2e9','#584D71')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_16','#FEC1FF','#9A659A')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_17','#F9C5A2','#886146')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_18','#98FFB4','#488D5A')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_19','#6EEABE','#306D57')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_20','#A2B4FF','#3A4265')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_21','#A783F9','#412F6A')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_22','#74bbfb','#3E668A')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_23','#a1d7c9','#46675F')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_24','#f2dea4','#BBA052')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_25','#efc0fe','#E086FD')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_26','#ffdac1','#7e4f09')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_27','#fff2cc','#736409')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_28','#e2F0cb','#657546')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_29','#a58d7f','#7F5943')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_30','#3E314C','#110022')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_31','#77dd77','#56A156')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_32','#f7cac9','#C8A4A3')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_33','#FCB2BE','#fc6c85')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_34','#96B2BE','#62757D')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_35','#97BE96','#637D62')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_36','#B6BE96','#787D62')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_37','#C4A2A0','#9E8382')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_38','#C8BAD4','#766D7D')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_39','#efc0fe','#E086FD')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_40','#e2F0cb','#657546')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_41','#343B4F','#050d25')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_42','#644646','#2b0202')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_43','#d90166','#8D0143')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_44','#355633','#062e03')
INSERT INTO APP_COLORS (IDENTIFIER,COLOR,DARK_COLOR) 
VALUES ('SUBJECT_COLOR_45','#316B74','#00424B')
GO
CREATE TABLE TEACHERS
(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NAME VARCHAR(200) NOT NULL
)
GO
CREATE TABLE GROUPS
(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
GUID UNIQUEIDENTIFIER DEFAULT newid() UNIQUE NOT NULL,
NAME VARCHAR(50) NOT NULL UNIQUE
)
GO
CREATE TABLE SUBJECTS
(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
GUID UNIQUEIDENTIFIER DEFAULT newid() UNIQUE NOT NULL,
NAME VARCHAR(200),
COLOR_ID INT FOREIGN KEY REFERENCES APP_COLORS
)
GO
CREATE TABLE TEACHER_SUBJECTS
(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TEACHER_ID INT FOREIGN KEY REFERENCES TEACHERS,
SUBJECT_ID INT FOREIGN KEY REFERENCES SUBJECTS
)
GO
CREATE TABLE INSCRIPTIONS
(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
USER_ID INT FOREIGN KEY REFERENCES USERS,
TEACHER_SUBJECTS_ID INT FOREIGN KEY REFERENCES TEACHER_SUBJECTS,
GROUP_ID INT FOREIGN KEY REFERENCES GROUPS
)
GO
CREATE TABLE GRADES
(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
INSCRIPTION_ID INT FOREIGN KEY REFERENCES INSCRIPTIONS,
PARTIAL INT NOT NULL,
NUMERIC_SCORE INT NOT NULL,
TEXT_SCORE VARCHAR(5) NOT NULL
)
GO
CREATE TABLE CLASS_TIMES
(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TEACHER_SUBJECT_ID INT FOREIGN KEY REFERENCES TEACHER_SUBJECTS,
DAY_ID INT NOT NULL FOREIGN KEY REFERENCES DAYS,
BEGIN_TIME TIME NOT NULL,
END_TIME TIME NOT NULL
)
GO
CREATE PROCEDURE SP_GET_USER_ID (@USER VARCHAR(100))
AS
BEGIN
	SELECT ID FROM USERS WHERE BOLETA=@USER OR MAIL=@USER;
END
GO
CREATE PROCEDURE SP_CHECK_IF_BANNED (@USER_ID INT,@IS_BANNED BIT OUTPUT)
AS
BEGIN
DECLARE @STRIKES INT=0;
SELECT @STRIKES=STRIKES FROM USERS WHERE ID=@USER_ID
IF @STRIKES>=3
BEGIN
	UPDATE USERS SET BANNED=1 WHERE ID=@USER_ID
	SELECT  @IS_BANNED=1;
END ELSE 
BEGIN
	SELECT @IS_BANNED=0;
END
END;
GO
CREATE PROCEDURE SP_LOGIN (
@MAIL VARCHAR(100),
@BOLETA VARCHAR(20),
@PASSWORD_PIN VARCHAR(50),
@SCHOOL_NAME VARCHAR(100),
@DEVICE_KEY VARCHAR(100)
)
AS
BEGIN
DECLARE @USER_ID INT=0;
IF @BOLETA IS NOT NULL 
BEGIN
	select @USER_ID=ID From USERS where BOLETA=@BOLETA;
	IF @USER_ID<=0
		BEGIN
			SELECT 'SHOULD_ENROLL',''
			RETURN
		END 
END ELSE 
BEGIN
	select @USER_ID=ID From USERS where MAIL=@MAIL COLLATE Latin1_General_CS_AS;
	IF @USER_ID<=0
		BEGIN
			SELECT 'KO','Usuario o contraseña incorrectos'
			RETURN
		END 
END
DECLARE @REAL_PASSWORD VARCHAR(50)
select @REAL_PASSWORD=PASSWORD_PIN From USERS where ID=@USER_ID 
IF @REAL_PASSWORD!=@PASSWORD_PIN COLLATE Latin1_General_CS_AS
BEGIN
	SELECT 'KO','Usuario o contraseña incorrectos'
	RETURN
END
----------------
DECLARE @SCHOOL_ID INT =0;
IF @SCHOOL_NAME IS NOT NULL
BEGIN
SELECT @SCHOOL_ID=ID FROM SCHOOLS WHERE NAME=@SCHOOL_NAME
END ELSE
BEGIN
SELECT TOP 1 @SCHOOL_ID=SCHOOL_ID FROM USERS_SCHOOLS WHERE USER_ID=@USER_ID ORDER BY ID DESC
END

IF @SCHOOL_ID<=0
BEGIN
	SELECT 'INVALID_REQUEST','La escuela seleccionada es invalida'
	RETURN
END 
IF NOT EXISTS(SELECT ID FROM USERS_SCHOOLS WHERE USER_ID=@USER_ID AND SCHOOL_ID=@SCHOOL_ID)
	BEGIN
		SELECT 'KO','No estas registrado en este plantel, registrate para poder acceder'
		RETURN
	END ELSE
	BEGIN
		DECLARE @IS_BANNED BIT=0;
		EXEC SP_CHECK_IF_BANNED @USER_ID,@IS_BANNED OUTPUT
		IF @IS_BANNED=1
		BEGIN
			SELECT 'KO','Su usuario ha sido bloqueado debido a el mal uso de la aplicación.\n Si cree que se trata de un error contactenos en: jgarciag1404@alumno.ipn.mx'
		END
		ELSE 
		BEGIN
			UPDATE DEVICES SET LAST_TIME_SEEN=GETDATE() WHERE DEVICE_KEY=@DEVICE_KEY
			DECLARE @SCHOOL VARCHAR(MAX)
			SELECT @SCHOOL='{"HomePage":"'+HOME_PAGE+'","Name":"'+NAME+'","ImgPath":"'+IMG_PATH+'"}'
			FROM SCHOOLS WHERE ID=@SCHOOL_ID
			SELECT 'OK','Bienvenido','{"Boleta":"'+BOLETA+'","School":'+@SCHOOL+' }'
			FROM USERS WHERE ID=@USER_ID
		END
	END
END
GO
CREATE PROCEDURE SP_SIGNUP(
@BOLETA VARCHAR(20),
@NAME  VARCHAR(100),
@MAIL VARCHAR(100),
@PASSWORD_PIN VARCHAR(50),
@SCHOOL_NAME VARCHAR(100),
@DEVICE_KEY VARCHAR(100),
@BRAND VARCHAR(100),
@PLATFORM VARCHAR(100),
@MODEL  VARCHAR(100),
@D_NAME  VARCHAR(100),
@TYPE INT=1
)
AS
BEGIN
	DECLARE @SCHOOL_ID INT =0;
	SELECT @SCHOOL_ID=ID FROM SCHOOLS WHERE NAME=@SCHOOL_NAME
	IF @SCHOOL_ID<=0
	BEGIN
		SELECT 'INVALID_REQUEST','La escuela seleccionada es invalida'
	END ELSE 
	BEGIN
		DECLARE @USER_ID INT=0
		SELECT @USER_ID= ID FROM USERS WHERE BOLETA=@BOLETA
		IF @USER_ID>0
		BEGIN
			IF EXISTS(SELECT ID FROM USERS_SCHOOLS WHERE USER_ID=@USER_ID)
			BEGIN
				SELECT 'INVALID_REQUEST','Este usuario ya esta registrado'
			END 
		END ELSE
		BEGIN
			IF EXISTS(SELECT ID FROM USERS WHERE MAIL=@MAIL)
			BEGIN
				SELECT 'INVALID_REQUEST','Ya existe un usuario asocidado a este correo electrónico'
			END ELSE
			BEGIN
			
			INSERT INTO USERS(TYPE,NAME,BOLETA,MAIL,PASSWORD_PIN)
			VALUES (@TYPE,@NAME,@BOLETA,@MAIL,@PASSWORD_PIN);
			SELECT @USER_ID=SCOPE_IDENTITY();
			INSERT INTO USERS_SCHOOLS(SCHOOL_ID,USER_ID) VALUES (@SCHOOL_ID,@USER_ID)
			INSERT INTO DEVICES(USER_ID,DEVICE_KEY,BRAND,PLATFORM,MODEL,NAME) VALUES(@USER_ID,@DEVICE_KEY,@BRAND,@PLATFORM,@MODEL,@D_NAME)
			SELECT 'OK','Bienvenido :)'
			END
		END

	END
END;
GO
CREATE PROCEDURE SP_GET_ADD_TEACHER(
@NAME VARCHAR(200)
)
AS
BEGIN
	IF @NAME IS NULL OR LTRIM(RTRIM(@NAME))=''
	BEGIN
		SELECT 'INVALID_REQUEST'
		RETURN
	END
	DECLARE @TEACHER_ID INT=0
	SELECT @TEACHER_ID=ID FROM TEACHERS WHERE NAME=@NAME
	IF @TEACHER_ID>0
	BEGIN
		SELECT * FROM TEACHERS WHERE ID=@TEACHER_ID
	END ELSE
	BEGIN
		INSERT INTO TEACHERS(NAME) VALUES(@NAME)
		SELECT *FROM TEACHERS WHERE ID=SCOPE_IDENTITY()
	END
END
GO
CREATE PROCEDURE SP_GET_ADD_SUBJECT (
@USER_ID INT,
@GROUP_NAME VARCHAR(50),
@SUBJECT_NAME VARCHAR(200),
@TEACHER_ID INT
)
AS
BEGIN
	IF @SUBJECT_NAME IS NULL OR LTRIM(RTRIM(@SUBJECT_NAME))='' OR
	   @GROUP_NAME IS NULL OR LTRIM(RTRIM(@GROUP_NAME))='' OR
	   NOT EXISTS(SELECT ID FROM TEACHERS WHERE ID=@TEACHER_ID) OR
	   NOT EXISTS (SELECT ID FROM USERS WHERE ID=@USER_ID)
	BEGIN
		SELECT 'INVALID_REQUEST'
		RETURN
	END
	
	DECLARE @GROUP_ID INT=0
	SELECT @GROUP_ID=ID FROM GROUPS WHERE NAME=@GROUP_NAME
	IF @GROUP_ID<=0 
	BEGIN
		INSERT INTO GROUPS(NAME) VALUES(@GROUP_NAME)
		SELECT @GROUP_ID=SCOPE_IDENTITY()
	END 

	DECLARE @SUBJECT_ID INT=0
	SELECT @SUBJECT_ID=ID FROM SUBJECTS WHERE NAME=@SUBJECT_NAME 
	IF @SUBJECT_ID<=0 
	BEGIN
		DECLARE @COLOR_ID INT=0
		DECLARE @SUFIX VARCHAR(2) ='10'
		SELECT @SUFIX=RIGHT(@GROUP_NAME, 2)	
		SELECT @COLOR_ID=ID FROM APP_COLORS
		WHERE IDENTIFIER='SUBJECT_COLOR_'+@SUFIX

		INSERT INTO SUBJECTS(NAME,COLOR_ID) VALUES(@SUBJECT_NAME,@COLOR_ID)
		SELECT @SUBJECT_ID=SCOPE_IDENTITY()
	END 

	DECLARE @TEACHER_SUBJECTS_ID INT =0
	SELECT @TEACHER_SUBJECTS_ID=ID FROM TEACHER_SUBJECTS WHERE SUBJECT_ID=@SUBJECT_ID AND TEACHER_ID=@TEACHER_ID
	IF @TEACHER_SUBJECTS_ID<=0
	BEGIN
		INSERT INTO TEACHER_SUBJECTS(SUBJECT_ID,TEACHER_ID) VALUES (@SUBJECT_ID,@TEACHER_ID)
		SELECT @TEACHER_SUBJECTS_ID=SCOPE_IDENTITY()
	END

	IF NOT EXISTS(SELECT ID FROM INSCRIPTIONS WHERE USER_ID=@USER_ID AND GROUP_ID=@GROUP_ID AND @TEACHER_SUBJECTS_ID=TEACHER_SUBJECTS_ID )
	BEGIN
		INSERT INTO INSCRIPTIONS(TEACHER_SUBJECTS_ID,USER_ID,GROUP_ID) VALUES (@TEACHER_SUBJECTS_ID,@USER_ID,@GROUP_ID)
	END

	SELECT SUBJECTS.ID,GUID,@TEACHER_ID,NAME,@GROUP_NAME,
	APP_COLORS.COLOR,APP_COLORS.DARK_COLOR
	FROM SUBJECTS
	INNER JOIN APP_COLORS ON APP_COLORS.ID=SUBJECTS.COLOR_ID
	WHERE SUBJECTS.ID=@SUBJECT_ID

END
GO
CREATE PROCEDURE SP_GET_ADD_CLASSTIME(
@TEACHER_ID INT,
@SUBJECT_ID INT,
@DAY_ID INT,
@BEGIN_TIME TIME,
@END_TIME TIME
)
AS
BEGIN
IF NOT EXISTS(SELECT ID FROM SUBJECTS WHERE ID=@SUBJECT_ID) OR
   NOT EXISTS(SELECT ID FROM DAYS WHERE ID=@DAY_ID)
   BEGIN
	SELECT 'INVALID_REQUEST'
	RETURN
END 

DECLARE @TEACHER_SUBJECT_ID INT=0
SELECT @TEACHER_SUBJECT_ID=ID FROM TEACHER_SUBJECTS WHERE
SUBJECT_ID=@SUBJECT_ID AND TEACHER_ID=@TEACHER_ID

DECLARE @CLASSTIME_ID INT=0
SELECT @CLASSTIME_ID=ID FROM CLASS_TIMES
WHERE TEACHER_SUBJECT_ID=@TEACHER_SUBJECT_ID AND DAY_ID=@DAY_ID AND BEGIN_TIME=@BEGIN_TIME AND END_TIME=@END_TIME

IF @CLASSTIME_ID<=0
BEGIN
	INSERT INTO CLASS_TIMES(TEACHER_SUBJECT_ID,DAY_ID,BEGIN_TIME,END_TIME)
	VALUES(@TEACHER_SUBJECT_ID,@DAY_ID,@BEGIN_TIME,@END_TIME)
	SELECT @CLASSTIME_ID=SCOPE_IDENTITY()
END
	SELECT CLASS_TIMES.ID,@SUBJECT_ID,DAY_ID,BEGIN_TIME,END_TIME,GROUPS.NAME
	FROM CLASS_TIMES
	INNER JOIN INSCRIPTIONS ON INSCRIPTIONS.TEACHER_SUBJECTS_ID=@TEACHER_SUBJECT_ID
	INNER JOIN GROUPS ON GROUPS.ID=INSCRIPTIONS.GROUP_ID
	WHERE CLASS_TIMES.ID=@CLASSTIME_ID
END
GO
CREATE PROCEDURE SP_GET_ADD_CAREER(
@USER VARCHAR(100),
@CAREER_NAME VARCHAR(100)
)
AS
BEGIN
DECLARE @CAREER_ID INT=0
SELECT @CAREER_ID=ID FROM CAREERS WHERE NAME=@CAREER_NAME
IF @CAREER_ID<=0
BEGIN
	INSERT INTO CAREERS(NAME) VALUES (@CAREER_NAME)
	SELECT @CAREER_ID=SCOPE_IDENTITY()
END

DECLARE @USER_ID INT=0
SELECT @USER_ID=ID From USERS where BOLETA=@USER OR MAIL=@USER;
UPDATE USERS_SCHOOLS SET CAREER_ID=@CAREER_ID WHERE USER_ID=@USER_ID
SELECT 'OK',@CAREER_ID
END
GO
CREATE PROCEDURE SP_UPDATE_GRADES(
@PARTIAL INT,
@NUMERIC_SCORE INT,
@TEXT_SCORE VARCHAR(5),
@USER VARCHAR(100),
@GROUP VARCHAR(50)
)
AS 
BEGIN
DECLARE @USER_ID INT=0
SELECT @USER_ID=ID FROM USERS WHERE BOLETA=@USER OR MAIL=@USER;
IF @USER_ID<=0
BEGIN
	SELECT 'INVALID_REQUEST',''
END

DECLARE @GROUP_ID INT=0
SELECT @GROUP_ID=ID FROM GROUPS WHERE NAME=@GROUP
IF @GROUP_ID<=0
BEGIN
	SELECT 'INVALID_REQUEST',''
END

DECLARE @INSCRIPTION_ID INT=0
SELECT @INSCRIPTION_ID=ID FROM INSCRIPTIONS WHERE USER_ID=@USER_ID AND GROUP_ID=@GROUP_ID
IF @INSCRIPTION_ID<=0
BEGIN
	SELECT 'INVALID_REQUEST',''
END

DECLARE @GRADE_ID INT=0
SELECT @GRADE_ID=ID FROM GRADES WHERE INSCRIPTION_ID=@INSCRIPTION_ID AND PARTIAL=@PARTIAL

IF @GRADE_ID<=0
BEGIN
INSERT INTO GRADES(INSCRIPTION_ID,PARTIAL,NUMERIC_SCORE,TEXT_SCORE) 
VALUES (@INSCRIPTION_ID,@PARTIAL,@NUMERIC_SCORE,@TEXT_SCORE)
SELECT @GRADE_ID=SCOPE_IDENTITY()
END ELSE
BEGIN
UPDATE GRADES SET PARTIAL=@PARTIAL,NUMERIC_SCORE=@NUMERIC_SCORE,TEXT_SCORE=@TEXT_SCORE
WHERE ID=@GRADE_ID
END

DECLARE @SUBJECTS_ID INT =0
SELECT @SUBJECTS_ID=GROUP_ID FROM INSCRIPTIONS WHERE ID=@INSCRIPTION_ID

SELECT ID,@SUBJECTS_ID,NUMERIC_SCORE,TEXT_SCORE,PARTIAL FROM GRADES WHERE ID=@GRADE_ID
END
GO