EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'APP_AUTHENTICATION'
GO
use [APP_AUTHENTICATION];
GO
use [master];
GO
USE [master]
GO
ALTER DATABASE [APP_AUTHENTICATION] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
USE [master]
GO
/****** Object:  Database [APP_AUTHENTICATION]    Script Date: 11/08/2020 11:01:05 p. m. ******/
DROP DATABASE [APP_AUTHENTICATION]
GO
CREATE DATABASE APP_AUTHENTICATION
GO
USE APP_AUTHENTICATION
GO
CREATE TABLE USER_TYPES
(
 ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 DESCRIPTION VARCHAR(100) NOT NULL
)
GO
INSERT INTO USER_TYPES VALUES('Regular user');
INSERT INTO USER_TYPES VALUES('Tester');
INSERT INTO USER_TYPES VALUES('Admin');
GO
CREATE TABLE USERS
(
 ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 GUID UNIQUEIDENTIFIER DEFAULT newid() UNIQUE NOT NULL,
 TYPE INT FOREIGN KEY REFERENCES USER_TYPES,
 NAME VARCHAR(100) NOT NULL,
 BOLETA VARCHAR(20) UNIQUE NOT NULL,
 MAIL VARCHAR(100)  UNIQUE NOT NULL,
 PASSWORD_PIN VARCHAR(50) NOT NULL,
 STRIKES INT DEFAULT 0,
 BANNED BIT DEFAULT 0,
 DELETED BIT DEFAULT 0
)
GO
CREATE TABLE DEVICES
(
 ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 GUID UNIQUEIDENTIFIER DEFAULT newid() UNIQUE NOT NULL,
 USER_ID INT FOREIGN KEY REFERENCES USERS NOT NULL,
 DEVICE_KEY  VARCHAR(100) UNIQUE NOT NULL,
 BRAND VARCHAR(100) NOT NULL DEFAULT 'GENERIC',
 PLATFORM VARCHAR(100) NOT NULL DEFAULT 'GENERIC',
 MODEL VARCHAR(100) NOT NULL DEFAULT 'GENERIC',
 NAME VARCHAR(100) NOT NULL DEFAULT 'GENERIC',
 LAST_TIME_SEEN DATETIME NOT NULL DEFAULT GETDATE(),
 ENABLED BIT DEFAULT 1,

)
GO
INSERT INTO USERS
VALUES(newid(),2,'Jonathan García','2015130425','blum.desarrollo.jonathang@gmail.com','1123',0,0,0);
